#:schema node_modules/wrangler/config-schema.json
name = "kanye-rest"
workers_dev = false
main = "src/index.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]
route = "api.kanye.rest/*"